import type {MetaFunction} from '@shopify/remix-oxygen';

export const meta: MetaFunction = () => {
  return [{title: 'Terms and Conditions - Simple Chat'}];
};

export default function TermsAndConditions() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-16">
      <h1 className="text-4xl font-bold text-gray-900 mb-4">
        Terms and Conditions
      </h1>
      <p className="text-gray-500 mb-8">The legal stuff</p>

      <div className="prose prose-gray max-w-none">
        <p>
          These Terms of Service (these "Terms") are part of the overall
          Agreement (as defined below) between you ("you" or "Customer") and SA
          Inc., a company based in Ontario, Canada ("Simple Chat"). The
          Agreement governs your use of the Simple Chat platform, analytics,
          information, applications, websites, payments functionality, and other
          products and services (collectively, the "Services").
        </p>

        <p>
          This Agreement is effective as of the date you install Simple Chat
          from the Shopify app store and/or the date you enter a Customer Order
          with Simple Chat incorporating these Terms (the "Effective Date").
        </p>

        <p>
          By accessing or using the Services in any manner, you agree to the
          following, in order of precedence, which collectively form the
          "Agreement":
        </p>
        <ol>
          <li>All terms and conditions in these Terms;</li>
          <li>Our privacy policy ("Privacy Policy"), cookie policy; and</li>
          <li>
            Any other standard policies or guidelines posted in our Services.
          </li>
        </ol>

        <p>
          If you use the Services on behalf of a company or other entity, then
          "you" includes you personally and your company, and you represent and
          warrant that (a) you are an authorized representative of the entity
          with the authority to bind the entity to the Agreement, and (b) you
          agree to the Agreement on the entity's behalf.
        </p>

        <h2>1 - Definitions</h2>
        <p>
          The following capitalized terms have the following meanings in this
          Agreement:
        </p>
        <ul>
          <li>
            <strong>"Chat"</strong> means an individual or business entity
            registered on the Services as a Chat of a respective Merchant.
          </li>
          <li>
            <strong>"Chat Sales Revenue"</strong> means the total amount of
            proceeds received from the sale of products or services by a
            Merchant and generated by a Merchant's Chats.
          </li>
          <li>
            <strong>"Authorized User"</strong> means any individual who uses the
            Services on Customer's behalf.
          </li>
          <li>
            <strong>"Customer Data"</strong> means data in electronic form input
            into or collected through the Services by Customer.
          </li>
          <li>
            <strong>"Documentation"</strong> means Simple Chat's standard manual
            related to the use of the Services.
          </li>
          <li>
            <strong>"End Users"</strong> means individuals or businesses who
            interact with Customer through hyperlinks or other software enabled
            by Customer's use of the Services.
          </li>
          <li>
            <strong>"Fees"</strong> means the fees for access to and use of the
            Services.
          </li>
          <li>
            <strong>"Merchant"</strong> means an e-commerce or other business
            entity that is contractually obligated to pay a commission, referral
            fee, or similar compensation.
          </li>
          <li>
            <strong>"Term"</strong> refers to the duration of this Agreement.
          </li>
          <li>
            <strong>"Transaction"</strong> means a purchase of a Merchant's
            products and services logged by the Services.
          </li>
        </ul>

        <h2>2 - The Services</h2>
        <h3>Account Terms</h3>
        <p>
          In order to access most features of the Services, you must register
          for a Simple Chat account ("Account") by providing your entity's full
          legal name, current address, phone number, a valid email address, and
          any other information indicated as required. You may only register on
          behalf of a corporation, the sole proprietorship of an individual 18
          years or older, or another entity authorized to do business pursuant
          to applicable law.
        </p>

        <h3>Use of the Services</h3>
        <p>
          During the Term and provided that this Agreement has not been
          terminated, and in consideration of the payment of the Fees, you may
          access the Services for the purpose of using Services pursuant and
          subject to the terms of this Agreement.
        </p>

        <h3>Services Modifications</h3>
        <p>
          Simple Chat, in its sole discretion, may modify the Services at any
          time, including without limitation by ceasing operation of the
          Services in their entirety.
        </p>

        <h2>3 - Orders & Fees</h2>
        <p>
          Merchant shall pay Simple Chat the fees for the access to and use of
          the Services ("Fees") specified in the Customer Order. Fees may depend
          on the number of workflow operations, the number of active workflows,
          and are further based on the length of the Term, number of Authorized
          Users, and data volume.
        </p>
        <p>
          All Fees are exclusive of, and Merchant is responsible for, applicable
          sales, use, excise, export, or other applicable taxes, except for
          taxes on the net income of Simple Chat.
        </p>

        <h2>4 - Third-Party Content and Services</h2>
        <p>
          The Customer may configure the Services to integrate and/or interact
          with third-party data or platforms ("Third Party Platforms"). It is
          Customer's responsibility to analyze and interpret any third-party
          contractual terms applicable to Customer's use of the Services.
        </p>
        <p>
          Simple Chat has no affiliation, endorsement, or sponsorship by any
          other Third Party Platform. Simple Chat makes no endorsement of such
          third parties, nor any representation or warranty regarding anything
          that takes place between Customer and any such third parties.
        </p>

        <h2>5 - Customer Data & Privacy</h2>
        <h3>License Grant</h3>
        <p>
          Customer grants Simple Chat a non-exclusive right and license to use,
          copy, reproduce, modify, adapt, publish, and display the Customer Data
          to provide the Services, enhance the Services, collect and deliver
          market insights, and for other business purposes.
        </p>

        <h3>Privacy Policy</h3>
        <p>
          The Privacy Policy applies only to the Services and does not apply to
          any third-party website or service linked to the Services.
        </p>

        <h3>Data Deletion</h3>
        <p>
          Simple Chat may permanently erase Customer Data if Customer's account
          is delinquent, suspended, or terminated for 30 days or more.
        </p>

        <h2>6 - Customer's Responsibilities and Restrictions</h2>
        <p>Customer shall not:</p>
        <ul>
          <li>
            Use the Services for service bureau or time-sharing purposes or
            allow third parties to exploit the Services
          </li>
          <li>
            Provide Services passwords or other log-in information to any third
            party
          </li>
          <li>
            Share non-public Services features or content with any third party
          </li>
          <li>
            Access the Services in order to build a competitive product or
            service
          </li>
        </ul>
        <p>
          Customer shall take reasonable steps to prevent unauthorized access to
          the Services, including protecting its passwords and other log-in
          information.
        </p>

        <h2>7 - IP and Feedback</h2>
        <p>
          Simple Chat retains all rights, title, and interest in and to the
          Services, including without limitation all software, system software,
          and applications used to provide the Services.
        </p>
        <p>
          "Feedback" refers to any suggestion or idea for improving or otherwise
          modifying any of Simple Chat's products or services. Simple Chat has
          not agreed to and does not agree to treat as confidential any Feedback
          that Customer or Authorized Users provide to Simple Chat.
        </p>

        <h2>8 - Confidential Information</h2>
        <p>
          "Confidential Information" refers to any document Simple Chat marks
          "Confidential," the Documentation, this Agreement, Customer Order and
          any communications between Simple Chat and Customer, and any other
          nonpublic, sensitive information disclosed by Simple Chat.
        </p>
        <p>
          Customer shall not use Confidential Information for any purpose other
          than in connection with its use of the Services for its ordinary
          business purposes.
        </p>

        <h2>9 - Representations & Warranties</h2>
        <p>Simple Chat represents and warrants that:</p>
        <ul>
          <li>
            It is the owner of the Services and of each and every component
            thereof
          </li>
          <li>
            It has and will maintain the full power and authority to grant the
            rights granted in this Agreement
          </li>
          <li>
            The Services do not and will not infringe the intellectual property
            rights of any third party
          </li>
        </ul>

        <h2>10 - Indemnification</h2>
        <p>
          Customer shall defend, indemnify, and hold harmless Simple Chat
          against any third-party claim, suit, or proceeding arising out of or
          related to Customer's breach of its representations or warranties,
          Customer Data infringing the rights of such third party, or Customer's
          alleged or actual use of, misuse of, or failure to use the Services.
        </p>

        <h2>11 - Limitation of Liability</h2>
        <p>
          Simple Chat's liability arising out of or related to this Agreement
          will not exceed the amount of the Fees actually paid by Customer to
          Simple Chat in a period of twelve months immediately preceding the
          date on which the claim arose.
        </p>
        <p>
          In no event will Simple Chat be liable to Customer for any
          consequential, indirect, special, incidental, or punitive damages
          arising out of or related to this Agreement.
        </p>

        <h2>12 - Term and Termination</h2>
        <p>
          The term of this Agreement shall commence on the Effective Date and
          continue for the initial term specified in the Customer Order.
          Following its expiration, the Term will renew automatically for
          successive terms, unless either party provides notice of non-renewal
          thirty (30) or more days before the renewal date.
        </p>
        <p>Either party may terminate this Agreement if the other party:</p>
        <ul>
          <li>
            Fails to cure any material breach within thirty (30) days after
            written notice
          </li>
          <li>Ceases operation without a successor</li>
          <li>Seeks protection under any bankruptcy proceeding</li>
        </ul>

        <h2>13 - Publicity</h2>
        <p>
          Customer agrees to permit Simple Chat to use Customer's name and
          trademarks and service marks to identify Customer as Simple Chat's
          customer on the Website, in sales and marketing materials and
          activities.
        </p>

        <h2>14 - Miscellaneous</h2>
        <p>
          <strong>Independent Contractors:</strong> The parties are independent
          contractors and will so represent themselves in all regards. Neither
          party is the agent of the other.
        </p>
        <p>
          <strong>Notices:</strong> Simple Chat may send notices to Customer's
          email address(es) in Customer's Account. Customer may send notices to
          SA Inc., 1905 Lauder Dr, Ottawa, ON K2A 1A9, Canada, Attn: Simple Chat
          Legal, with a copy sent by email to admin@simple-chat.com.
        </p>
        <p>
          <strong>Choice of Law & Jurisdiction:</strong> This Agreement is a
          contract made under, governed by, and construed in accordance with,
          the laws of the Province of Ontario and the federal laws of Canada
          applicable in the Province of Ontario.
        </p>
        <p>
          <strong>Entire Agreement:</strong> This Agreement sets forth the
          entire agreement of the parties and supersedes all prior or
          contemporaneous writings, negotiations, and discussions with respect
          to its subject matter.
        </p>
        <p>
          <strong>Amendment:</strong> Simple Chat may amend this Agreement from
          time to time by posting an amended version on its Website and
          Application. Such amendment will be deemed accepted and become
          effective immediately. Customer's continued use of the Services
          following the effective date of an amendment will confirm Customer's
          consent thereto.
        </p>

        <p className="text-sm text-gray-500 mt-8">
          By installing Simple Chat, you acknowledge that you have read this
          Agreement, understand it, and agree to be bound by its terms.
        </p>
      </div>
    </div>
  );
}
